### ISSUE TITLE
RestClient::Forbidden: 403 Forbidden

### ISSUE THREAD

**Issue by john-cowhig-blinq** [joshnesbitt/google_url_shortener#4]
Recently started getting this error. 
```url = Google::UrlShortener::Url.new(:long_url => long_url)
=> #<Google::UrlShortener::Url:0x007f8e660e6c48
 @long_url=
  "http://www.example.com/">
[4] pry(main)> url.shorten!
RestClient::Forbidden: 403 Forbidden
from /Users/xxxxxx/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!'```

**Comment by joshnesbitt** [comment]
Thanks for reporting. Can you get more information regarding the request that's coming back from Google by any chance?

**Comment by martyn-w** [comment]
Hi @joshnesbitt we are having this issue too - I think Google may have recently (18th March 2015?) tweaked their API which is breaking this. After a bit of investigation, I think the issue is how the api key field is passed to the api. Currently this gem passes it as a data field:

	RestClient.post
		"https://www.googleapis.com/urlshortener/v1/url",
		"{\"key\":\"MY_API_KEY\",\"longUrl\":\"http://blog.josh-nesbitt.net\"}",
		"Accept"=>"application/json", "Accept-Encoding"=>"gzip, deflate", "Content-Length"=>"90", "Content-Type"=>"application/json"

Whereas I think Google now requires the key to be passed in the URL, e.g.

	RestClient.post
		"https://www.googleapis.com/urlshortener/v1/url?key=MY_API_KEY",
		"{\"longUrl\":\"http://blog.josh-nesbitt.net\"}",
		"Accept"=>"application/json", "Accept-Encoding"=>"gzip, deflate", "Content-Length"=>"90", "Content-Type"=>"application/json"

**Comment by martyn-w** [comment]
Just to note for anyone else having this issue, you can temporarily switched to a patched version of google_url_shortener by changing the reference in your Gemfile to `gem 'google_url_shortener', :git=>"https://github.com/CottageLabs/google_url_shortener.git"`

**Comment by joshnesbitt** [comment]
New gem here:

https://rubygems.org/gems/google_url_shortener

**Comment by rgperez** [comment]
Hi @joshnesbitt !! I'm having this issue too. I upgraded to 0.0.9 but:

RestClient.post "https://www.googleapis.com/urlshortener/v1/url?key=MY-PERSONAL-KEY", "{\"longUrl\":\"http://www.101empresas.com/empresa\"}", "Accept"=>"application/json", "Accept-Encoding"=>"gzip, deflate", "Content-Length"=>"48", "Content-Type"=>"application/json"
# => 403 Forbidden | application/json 304 bytes

I've ensured myself that my personal key is correct. Any idea?????

thanks in advance!

**Comment by joshnesbitt** [comment]
@rgperez I believe it's because you've not allowed access to the shortener API despite having a valid key. Have you enabled this screen?

![screen shot 2015-03-25 at 22 07 01](https://cloud.githubusercontent.com/assets/33054/6836587/6d5402d8-d33b-11e4-81f8-09e329aa04b0.png)

**Comment by joshnesbitt** [comment]
I've also pushed another version of the gem to output any request issues to help you debug it further. E.g:

```
403 Forbidden: {
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "accessNotConfigured",
    "message": "Access Not Configured. The API (URL Shortener API) is not enabled for your project. Please use the Google Developers Console to update your configuration.",
    "extendedHelp": "https://console.developers.google.com"
   }
  ],
  "code": 403,
  "message": "Access Not Configured. The API (URL Shortener API) is not enabled for your project. Please use the Google Developers Console to update your configuration."
 }
}
```

**Comment by rgperez** [comment]
Perfect!!!!!
Muchas gracias

**Comment by nhattan** [comment]
Having this issue again.

**Comment by joshnesbitt** [comment]
What error are you getting @nhattan?

**Comment by nhattan** [comment]
@joshnesbitt `RestClient::Forbidden: 403 Forbidden` I guess it's because Google turned off the shortener: https://developers.google.com/url-shortener/v1/getting_started

**Comment by joshnesbitt** [comment]
I'd say that would do it 😂
