### ISSUE TITLE
It breaks with custom URIs

### ISSUE THREAD

**Issue by rhymes** [joshnesbitt/google_url_shortener#9]
I'm honestly not sure what's supposed to do with non-HTTP custom URIs but I thought you might want to know that it raises an error if given a custom URI:

```ruby
[13] pry(main)> url
=> "ovsapp://foobar"
[14] pry(main)> Google::UrlShortener.shorten!(url)
RestClient.post "https://www.googleapis.com/urlshortener/v1/url?key=MY_KEY", "{\"longUrl\":\"ovsapp://foobar\"}", "Accept"=>"application/json", "Accept-Encoding"=>"gzip, deflate", "Content-Length"=>"29", "Content-Type"=>"application/json", "User-Agent"=>"rest-client/2.0.0 (darwin16.1.0 x86_64) ruby/2.3.3p222"
# => 400 BadRequest | application/json 160 bytes
#<RestClient::BadRequest: 400 Bad Request>
NoMethodError: undefined method `[]' for nil:NilClass
from /Users/rhymes/.rvm/gems/ruby-2.3.3/gems/google_url_shortener-1.1.0/lib/google/url_shortener/url.rb:27:in `encode!'
```

it seems like https://github.com/joshnesbitt/google_url_shortener/blob/master/lib/google/url_shortener/url.rb#L25 returns nil as response, and then at line https://github.com/joshnesbitt/google_url_shortener/blob/master/lib/google/url_shortener/url.rb#L27 it breaks.

**Comment by gerryhd** [comment]
Did anyone give this any following? I'm getting the same problem with `post(params)` returning nil

**Comment by joshnesbitt** [comment]
I've not used this for a while to be honest, and none of the tests cover app protocols etc. If you want to have a stab at a PR I'd welcome it, but I don't have time to take a look now, sorry!

**Comment by gerryhd** [comment]
That's alright actually, it was a problem with my project configuration on Google console. Thank you for stopping by tho, appreciate it.

If anyone ever stumbles upon a similar problem, make sure you're allowing your server's IP in the google developer console. 
In the OP's case, the post(params) method will try to make a request for said url but (logically?) it will fail.

**Comment by bf4** [comment]
Sounds like this can be closed?

**Comment by joshnesbitt** [comment]
Yup thanks @bf4!
